payment-item: '[TextComponentImpl{content="Teleport Crystal", style=StyleImpl{obfuscated=false,
  bold=false, strikethrough=false, underlined=false, italic=false, color=NamedTextColor{name="light_purple",
  value="#ff55ff"}, shadowColor=null, clickEvent=null, hoverEvent=null, insertion=null,
  font=null}, children=[]}]'

paid-message: §a§lMinevane §cYou have used a §dTeleport Crystal
dropped-item-message: §a§lMinevane §cPick up your §dTeleport Crystal
no-payment-item-message: §a§lMinevane §cYou need a §dTeleport Crystal§c to teleport

all-warps-free: false
free-warps:
- admin
- newplayerarea